# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

# See: https://golangci-lint.run/docs/linters/
linters:
  default: standard
  enable:
    - dogsled
    - dupl
    - gocritic
    - godot
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - nonamedreturns
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - unparam
    - whitespace
    - wsl_v5
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

# See: https://golangci-lint.run/docs/formatters/
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - manala/app
        - manala/internal

# See: https://golangci-lint.run/docs/configuration/file/#issues-configuration
issues:
  max-same-issues: 10
