linters:
  # See: https://golangci-lint.run/usage/linters/
  enable:
    - dogsled
    - dupl
    - exportloopref
    - gocritic
    - godot
    - gofmt
    - goimports
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - nonamedreturns
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - stylecheck
    - testpackage
    - testifylint
    - thelper
    - unconvert
    - unparam
    - whitespace
    - wsl

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  max-same-issues: 10
