before:
  hooks:
    - go mod download

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^typo:'
      - '^misc:'
      - Merge pull request
      - Merge branch

builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: windows
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: manala
      name: homebrew-tap
    commit_author:
      name: manala-bot
      email: contact@manala.io
    folder: Formula
    homepage: https://github.com/manala/manala
    description: Let your project's plumbing up to date
    test: |
      system "#{bin}/manala --version"

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/manala/manala
    description: Let your project's plumbing up to date
    maintainer: Manala <contact@manala.io>
    license: MIT
    vendor: Manala
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    suggests:
      - git
