before:
  hooks:
    - go mod tidy
builds:
  - id: linux
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: windows
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^typo:'
      - '^misc:'
      - Merge pull request
      - Merge branch
brews:
  - tap:
      owner: manala
      name: homebrew-tap
    commit_author:
      name: manala-bot
      email: contact@manala.io
    folder: Formula
    homepage: https://github.com/manala/manala
    description: Let your project's plumbing up to date
    test: |
      system "#{bin}/manala --version"
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/manala/manala
    description: Let your project's plumbing up to date
    maintainer: Manala <contact@manala.io>
    license: MIT
    vendor: Manala
    formats:
      - deb
      - rpm
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Let your project's plumbing up to date
    description: |
      Manala synchronize some boring parts of your projects,
      such as makefile targets, virtualization and provisioning files...

      Recipes are pulled from a git repository, or a local directory.
    license: MIT
    grade: stable
    confinement: strict
    apps:
      manala:
        plugs: ["home", "network", "removable-media"]
    publish: true
