services:

  ######
  # Go #
  ######

  go:
    image: golang:${MANALA_GO_VERSION}-trixie
    volumes:
      - go:/go
      - .:/usr/src/manala
    working_dir: /usr/src/manala

  #################
  # Golangci-lint #
  #################

  golangci-lint:
    image: golangci/golangci-lint:v${MANALA_GOLANGCI_LINT_VERSION}
    environment:
      GOCACHE: /.cache/go
      GOMODCACHE: /.cache/mod
      GOLANGCI_LINT_CACHE: /.cache/golangci-lint
    volumes:
      - .:/app
      - golangci-lint:/.cache
    working_dir: /app

  ############
  # Zensical #
  ############

  zensical:
    image: zensical/zensical:${MANALA_ZENSICAL_VERSION}
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    command: serve --dev-addr 0.0.0.0:8000

  #######
  # Vhs #
  #######

  vhs:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/charmbracelet/vhs:v${MANALA_VHS_VERSION}
        RUN apt update && apt install -y git
    volumes:
      - go:/go
      - .:/usr/src/manala
    working_dir: /usr/src/manala

volumes:
  go:
  golangci-lint:
