manala:
  description: A recipe example

# @option {"label": "Option string"}
# @schema {"type": "string", "minLength": 3}
option_string: ~

# @option {"label": "Option enum"}
# @schema {"enum": [1, 2, "D"]}
option_enum: ~
