name: Documentation

on:
  push:
    branches:
      - master

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # See: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/10
          fetch-depth: 0
      - name: Deploy
        # See: https://github.com/mhausenblas/mkdocs-deploy-gh-pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
