name: Documentation
on:
  push:
    branches:
      - master
jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # See: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/10
          fetch-depth: 0
      - name: Deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
