name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # See: https://github.com/goreleaser/goreleaser-action#workflow
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
      - name: Set up snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          # See: https://github.com/samuelmeuli/action-snapcraft#log-in
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        env:
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          version: v1.9.2
          args: release
