name: Release

on:
  push:
    tags:
      - '*.*.*'

concurrency: release

jobs:

  release:
    name: Release
    strategy:
      fail-fast: false
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # See: https://github.com/goreleaser/goreleaser-action#workflow
          fetch-depth: 0
      - name: Dotenv
        uses: xom9ikk/dotenv@v2
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.MANALA_GO_VERSION }}
      - name: Goreleaser release
        uses: goreleaser/goreleaser-action@v5
        env:
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          version: v${{ env.MANALA_GORELEASER_VERSION }}
          args: >
            release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist/
          if-no-files-found: error

  packages:
    name: Packages
    needs:
      - release
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout packages
        uses: actions/checkout@v4
        with:
          repository: manala/packages
          token: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          path: packages
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: dist/
      - name: Import packages GPG private key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PACKAGES_GPG_PRIVATE_KEY }}
      - name: Apt packages
        run: |
          sudo apt-get -qq --yes install reprepro
          reprepro \
            --verbose \
            --basedir packages/apt \
            includedeb stable dist/*.deb
      - name: Aur packages
        run: |
          sudo add-apt-repository --yes ppa:michel-slm/kernel-utils
          sudo apt-get -qq --yes install pacman-package-manager libarchive-tools
          for file in dist/*.pkg.tar.zst ; do \
            arch=$(basename $file .pkg.tar.zst | sed 's/.*-//') ; \
            echo "Processing arch $arch..." && \
            mkdir -p packages/aur/stable/$arch && \
            cp dist/*-$arch.pkg.tar.zst packages/aur/stable/$arch && \
            repo-add \
              --verify \
              --sign \
              --new \
              --remove \
              --prevent-downgrade \
              packages/aur/stable/$arch/manala.db.tar.gz packages/aur/stable/$arch/*-$arch.pkg.tar.zst && \
            gpg --detach-sign --no-armor --batch --yes packages/aur/stable/$arch/*-$arch.pkg.tar.zst ; \
          done
      - name: Commit packages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: packages
          branch: main
          file_pattern: .
          commit_message: Update packages
