name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.5]
        goreleaser-version: [1.14.1]
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # See: https://github.com/goreleaser/goreleaser-action#workflow
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Goreleaser release
        uses: goreleaser/goreleaser-action@v3
        env:
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          version: v${{ matrix.goreleaser-version }}
          args: >
            release
      - name: Checkout packages
        uses: actions/checkout@v3
        with:
          repository: manala/packages
          token: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          path: packages
      - name: Import packages GPG private key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PACKAGES_GPG_PRIVATE_KEY }}
      - name: Install reprepro
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: reprepro
          cache: true
      - name: Reprepro include deb files
        env:
          REPREPRO_BASE_DIR: packages/apt
        run: |
          reprepro -V includedeb stable dist/*.deb
      - name: Commit packages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: packages
          branch: main
          commit_message: Update packages
