name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      # See: https://github.com/golangci/golangci-lint-action#how-to-use
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dotenv
        uses: xom9ikk/dotenv@v2
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.MANALA_GO_VERSION }}
          # See: https://github.com/golangci/golangci-lint-action/pull/704
          cache: false
      - name: Lint - GolangCI
        uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ env.MANALA_GOLANGCI_LINT_VERSION }}
          # See: https://github.com/golangci/golangci-lint-action/issues/297
          args: --verbose --timeout 3m

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dotenv
        uses: xom9ikk/dotenv@v2
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.MANALA_GO_VERSION }}
      - name: Test
        env:
          RICHGO_FORCE_COLOR: 1
        run: |
          go install github.com/kyoh86/richgo@v${{ env.MANALA_RICHGO_VERSION }}
          richgo test -v ./...

  build:
    name: Build
    needs:
      - lint
      - test
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # See: https://github.com/goreleaser/goreleaser-action#workflow
          fetch-depth: 0
      - name: Dotenv
        uses: xom9ikk/dotenv@v2
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.MANALA_GO_VERSION }}
      - name: Goreleaser build
        uses: goreleaser/goreleaser-action@v5
        env:
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        with:
          version: v${{ env.MANALA_GORELEASER_VERSION }}
          args: >
            build --snapshot
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          if-no-files-found: error
