name: Test

on:
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: 1.20.2
  GORELEASER_VERSION: 1.16.1
  GOLANGCI_LINT_VERSION: 1.52.0
  RICHGO_VERSION: 0.3.12

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # See: https://github.com/goreleaser/goreleaser-action#workflow
          fetch-depth: 0
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        if: matrix.os == 'macos-12'
        uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ env.GOLANGCI_LINT_VERSION }}
          args: --verbose --timeout 3m
      - name: Test
        env:
          RICHGO_FORCE_COLOR: 1
        run: |
          go install github.com/kyoh86/richgo@v${{ env.RICHGO_VERSION }}
          richgo test -v ./...
      - name: Goreleaser build
        if: matrix.os == 'macos-12'
        uses: goreleaser/goreleaser-action@v4
        env:
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        with:
          version: v${{ env.GORELEASER_VERSION }}
          args: >
            build --snapshot
      - name: Upload artifacts
        if: matrix.os == 'macos-12'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          if-no-files-found: error
