name: Test
on: [workflow_dispatch, pull_request]
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.3]
        goreleaser-version: [1.12.3]
        golangci-lint-version: [1.50.1]
        richgo-version: [0.3.10]
        os: [ubuntu-20.04, macos-11, windows-2022]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # See: https://github.com/goreleaser/goreleaser-action#workflow
          fetch-depth: 0
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ matrix.os }}-
      - name: Lint
        if: matrix.os == 'macos-11'
        uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ matrix.golangci-lint-version }}
      - name: Test
        run: |
          go install github.com/kyoh86/richgo@v${{ matrix.richgo-version }}
          richgo test -v ./...
      - name: Build
        if: matrix.os == 'macos-11'
        uses: goreleaser/goreleaser-action@v3
        env:
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        with:
          version: v${{ matrix.goreleaser-version }}
          args: >
            build --snapshot
      - name: Upload artifacts
        if: matrix.os == 'macos-11'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
